In [1]:
from lang import load_data_int_seq
from models.rl.env import IntegerSequenceEnv
from models.rl.agents.agent_mcts.main import train_mcts


%load_ext autoreload
%autoreload 2


In [2]:
output_lang, input_lang, train, X_test, y_test = load_data_int_seq()
train = train[:1]
env = IntegerSequenceEnv({"data": train, "output_length": 9, "input_lang": input_lang, "output_lang": output_lang, "penalty_at_end": True})

self.state
[-1, -1, -1, -1, -1, -1, -1, -1, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8]


In [3]:
train_mcts(env, num_epochs=1000, policy=None, test=False)

Testing Agent


c:\Users\danie\Code\ai\research company\integer-sequence\function-gen\models\rl\agents\agent_mcts\MCTS_node.py:263: RuntimeWarning: invalid value encountered in true_divide
  return probs / np.sum(probs)



Training Episodes: 0
Action: 8
State:
[[-1 -1 -1 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [12 -1 -1 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [12  3 -1 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [12  3  7 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [12  3  7  3 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [12  3  7  3  9 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [12  3  7  3  9  1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [12  3  7  3  9  1  0 -1 -1  0  1  2  3  4  5  6  7  8]
 [12  3  7  3  9  1  0  3 -1  0  1  2  3  4  5  6  7  8]
 [12  3  7  3  9  1  0  3  8  0  1  2  3  4  5  6  7  8]]
['7', '*', '6', '*', '9', '+', 't', '*', '0']
Step: 9
Return: -200.0


C:\Users\danie\anaconda3\lib\site-packages\torch\autograd\__init__.py:132: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:100.)
  allow_unreachable=True)  # allow_unreachable flag


Testing Agent

Training Episodes: 50
Action: 0
State:
[[-1 -1 -1 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0 -1 -1 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1 -1 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1  0 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1  0  1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1  0  1  0 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1  0  1  0  1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1  0  1  0  1  0 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1  0  1  0  1  0  1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1  0  1  0  1  0  1  0  0  1  2  3  4  5  6  7  8]]
['t', '+', 't', '+', 't', '+', 't', '+', 't']
Step: 9
Return: -820.0
Testing Agent

Training Episodes: 100
Action: 0
State:
[[-1 -1 -1 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0 -1 -1 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1 -1 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1  0 -1 -1 -1 -1 -1 -1  0  1  2  3  4  5  6  7  8]
 [ 0  1  0  1 -1 -1 -1 

# HillClimbingEnv

In [ ]:
from models.rl.agents.agent_mcts.env_archive.hill_climbing_env import HillClimbingEnv

In [ ]:
env = HillClimbingEnv()

In [ ]:
train_mcts(env, num_epochs=2, policy=policy)